name: sentinel2-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - openeo
  - requests
  - pandas
  - numpy
  - geopandas
  - rasterio
  - folium
  - matplotlib
  - cdsapi
  - xarray
  - scipy
  - shapely
  - scikit-learn
  - xgboost
  - netcdf4
  - h5netcdf
